spring:
  application:
    name: springboot-demo
  output:
    ansi:
      enabled: detect
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/demo_db
    username: demo_user
    password: demo_pass
#    hikari:
#      connection-test-query: select 1
#      connection-timeout: 10000
#      maximum-pool-size: 2
#      minimum-idle: 2
#  jpa:
#    open-in-view: true
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true
#        use_sql_comments: true
#        generate_statistics: true
#        dialect: org.hibernate.dialect.Oracle10gDialecte
  jackson:
    serialization:
      write-dates-as-timestamps: false
      write-durations-as-timestamps: true

server:
  port: 3030

logging.file: demo.log
logging:
  file:
    max-history: 10
    max-size: 50MB
  level:
    root: info
    org.springframework: info
    org.hibernate: info
    org.hibernate.SQL: debug
    com.example.demo: debug